<Project>
  <ItemGroup>
    <PackageVersion Include="Silk.NET.Windowing.Common" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Windowing.Glfw" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Input.Common" Version="2.22.0" />
    <PackageVersion Include="Silk.NET.Input.Glfw" Version="2.22.0" />
    <PackageVersion Include="Silk.NET.Maths" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.GLFW" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.WebGPU" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.WebGPU.Extensions.WGPU" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.WebGPU.Native.WGPU" Version="2.23.0" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.14.0" />
  </ItemGroup>
</Project>
