<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Skyline.Interaction.Gpu\Skyline.Interaction.Gpu.csproj" />
    <ProjectReference Include="..\..\src\Skyline.Interaction\Skyline.Interaction.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
</Project>
